/* GENERATED by games/_shared/sync.js — edit games/_shared/meta/ instead. */
"use strict";

/* Levels, stars and unlock gating.

   The model, following Bullpen: a game has TIERS (difficulties). Each tier has
   a numbered ladder of levels. Finishing level N unlocks level N+1 in that
   tier. A whole tier can itself be locked behind a requirement — that is the
   "secret Extreme levels unlock after 1,000 puzzles" mechanic.

   Star rule (the confirmed default):
     3 stars — solved under par, with no hints and no mistakes
     2 stars — solved with no hints and no mistakes, but over par
     1 star  — solved
   A game can override it entirely with config.starsFor, which is how
   candy-crush's score thresholds and potion-vials' move counts would fit.

   Two invariants the tests pin down, because getting them wrong is how a
   progression system quietly eats someone's Sunday:
     - stars and best times NEVER regress on a worse replay
     - a level, once unlocked, never re-locks */

(function (root, factory) {
  var api = factory();
  if (typeof module !== "undefined" && module.exports) module.exports = api;
  else root.MetaProgress = api;
})(typeof globalThis !== "undefined" ? globalThis : this, function () {

  var VERSION = 1;
  /* Bump to force the per-tier aggregate counters to be recomputed from the
     levels map. They are derived data, so rebuilding them is always safe. */
  var AGG_VERSION = 1;

  function defaultStars(res, par) {
    var clean = !res.hints && !res.mistakes;
    if (clean && par && res.ms <= par) return 3;
    if (clean) return 2;
    return 1;
  }

  function blank() {
    return {
      v: VERSION,
      tiers: {},          // tierKey -> { unlocked, levels: { n: {stars,bestMs,plays} } }
      totalStars: 0,
      solvedCount: 0,     // every win, replays included
      clearedCount: 0     // distinct levels cleared at least once
    };
  }

  function Progress(opts) {
    if (!(this instanceof Progress)) return new Progress(opts);
    this.store = opts.store;
    this.key = opts.key || "progress";
    this.tiers = opts.tiers || [];
    this.starsFor = opts.starsFor || defaultStars;
    this.state = this.store.get(this.key, null) || blank();
    if (this.state.v !== VERSION) this.state = blank();

    // Seed the "already open" set so the first win doesn't announce a tier
    // that was never actually locked.
    if (!this.state.openedTiers) {
      this.state.openedTiers = [];
      for (var i = 0; i < this.tiers.length; i++) {
        if (this.tiers[i].requires && this.isTierUnlocked(this.tiers[i].key)) {
          this.state.openedTiers.push(this.tiers[i].key);
        }
      }
    }
  }

  Progress.prototype.save = function () {
    this.store.set(this.key, this.state);
  };

  Progress.prototype.tierDef = function (tierKey) {
    for (var i = 0; i < this.tiers.length; i++) {
      if (this.tiers[i].key === tierKey) return this.tiers[i];
    }
    return null;
  };

  Progress.prototype.tierState = function (tierKey) {
    var t = this.state.tiers[tierKey];
    if (!t) {
      t = { unlocked: 1, levels: {} };
      this.state.tiers[tierKey] = t;
    }
    if (!t.levels) t.levels = {};
    if (!t.unlocked) t.unlocked = 1;
    return t;
  };

  Progress.prototype.level = function (tierKey, n) {
    var lv = this.tierState(tierKey).levels[n];
    return lv ? { stars: lv.stars || 0, bestMs: lv.bestMs || 0, plays: lv.plays || 0 }
              : { stars: 0, bestMs: 0, plays: 0 };
  };

  /* Per-tier aggregates: how many levels cleared, how many stars earned.

     A home screen wants seven pairs of numbers, not every level. Building the
     whole map to count it is fine at 40 levels a tier and absurd at 500 — it
     allocates one object per level on every render. So the counters are kept
     incrementally in the tier state and updated in recordWin().

     Backfilled once for anyone whose save predates them, from the levels map
     they already have, and then persisted — so the O(played) walk happens at
     most once per tier per install, not once per paint. */
  Progress.prototype.tierTotals = function (tierKey) {
    var t = this.tierState(tierKey);
    if (!t.agg || t.agg.v !== AGG_VERSION) {
      var cleared = 0, stars = 0;
      for (var k in t.levels) {
        if (!Object.prototype.hasOwnProperty.call(t.levels, k)) continue;
        var lv = t.levels[k];
        if (lv && lv.plays) cleared++;
        if (lv && lv.stars) stars += lv.stars;
      }
      t.agg = { v: AGG_VERSION, cleared: cleared, stars: stars };
      this.save();
    }
    return { cleared: t.agg.cleared, stars: t.agg.stars };
  };

  Progress.prototype.isUnlocked = function (tierKey, n) {
    if (!this.isTierUnlocked(tierKey)) return false;
    return n <= this.tierState(tierKey).unlocked;
  };

  /* A tier with no `requires` is always open. Otherwise every stated
     requirement must be met — {solved, cleared, stars} are all supported. */
  Progress.prototype.isTierUnlocked = function (tierKey) {
    var def = this.tierDef(tierKey);
    if (!def || !def.requires) return true;
    var r = def.requires;
    if (r.solved && this.state.solvedCount < r.solved) return false;
    if (r.cleared && this.state.clearedCount < r.cleared) return false;
    if (r.stars && this.state.totalStars < r.stars) return false;
    return true;
  };

  /* What's still missing before a locked tier opens — for the UI to render
     "Solve 42 more puzzles". Returns null once the tier is open. */
  Progress.prototype.tierGate = function (tierKey) {
    var def = this.tierDef(tierKey);
    if (!def || !def.requires || this.isTierUnlocked(tierKey)) return null;
    var r = def.requires, out = [];
    if (r.solved) out.push({ kind: "solved", have: this.state.solvedCount, need: r.solved });
    if (r.cleared) out.push({ kind: "cleared", have: this.state.clearedCount, need: r.cleared });
    if (r.stars) out.push({ kind: "stars", have: this.state.totalStars, need: r.stars });
    return out;
  };

  Progress.prototype.parFor = function (tierKey, n) {
    var def = this.tierDef(tierKey);
    if (!def) return 0;
    if (typeof def.par === "function") return def.par(n);
    return def.par || 0;
  };

  /* The single write path. res = {ms, hints, mistakes, par?}.
     Returns what the win screen needs to render. */
  Progress.prototype.recordWin = function (tierKey, n, res) {
    res = res || {};
    var par = res.par || this.parFor(tierKey, n);
    var t = this.tierState(tierKey);
    var def = this.tierDef(tierKey);
    var maxLevel = def && def.levels ? def.levels : n;

    /* Force the aggregates to exist BEFORE this level is written. Backfilling
       afterwards would count the new result once in the walk and once again in
       the delta below. */
    this.tierTotals(tierKey);

    var prev = t.levels[n] || { stars: 0, bestMs: 0, plays: 0 };
    var firstClear = !prev.plays;

    var earned = this.starsFor({
      ms: res.ms || 0,
      hints: res.hints || 0,
      mistakes: res.mistakes || 0,
      level: n,
      tier: tierKey
    }, par);
    earned = Math.max(0, Math.min(3, earned | 0));

    var prevStars = prev.stars || 0;
    var prevBestMs = prev.bestMs || 0;
    var isNewBest = !!res.ms && (!prevBestMs || res.ms < prevBestMs);

    // Monotone: a slower or messier replay never takes anything away.
    t.levels[n] = {
      stars: Math.max(prevStars, earned),
      bestMs: isNewBest ? res.ms : prevBestMs,
      plays: (prev.plays || 0) + 1
    };

    this.state.totalStars += Math.max(0, t.levels[n].stars - prevStars);
    this.state.solvedCount += 1;
    if (firstClear) this.state.clearedCount += 1;

    /* Keep the per-tier aggregates in step with the same deltas, so
       tierTotals() never has to walk the levels map again. */
    t.agg.stars += Math.max(0, t.levels[n].stars - prevStars);
    if (firstClear) t.agg.cleared += 1;

    var unlockedNext = false;
    if (n + 1 <= maxLevel && t.unlocked < n + 1) {
      t.unlocked = n + 1;
      unlockedNext = true;
    }

    // A win can push totals past a tier gate — report which tiers just opened.
    var opened = [];
    for (var i = 0; i < this.tiers.length; i++) {
      var tk = this.tiers[i].key;
      if (!this.tiers[i].requires) continue;
      var wasOpen = (this.state.openedTiers || []).indexOf(tk) >= 0;
      if (!wasOpen && this.isTierUnlocked(tk)) {
        if (!this.state.openedTiers) this.state.openedTiers = [];
        this.state.openedTiers.push(tk);
        opened.push(tk);
      }
    }

    this.save();

    return {
      stars: earned,
      bestStars: t.levels[n].stars,
      prevStars: prevStars,
      isNewBest: isNewBest,
      firstClear: firstClear,
      prevBestMs: prevBestMs,
      bestMs: t.levels[n].bestMs,
      par: par,
      unlockedNext: unlockedNext ? n + 1 : 0,
      unlockedTiers: opened,
      totalStars: this.state.totalStars,
      solvedCount: this.state.solvedCount
    };
  };

  /* Snapshot for a level-map screen. */
  /* Snapshot for a level-map screen.

     mapFor(key)            every level in the tier — fine at 40, wasteful at 500
     mapFor(key, from, len) one page of it, which is what a chunked map wants.
     The range form exists so a 500-level ladder never has to allocate 500
     objects to draw 50 tiles. Omitting the range keeps the original behaviour,
     so existing callers are unaffected. */
  Progress.prototype.mapFor = function (tierKey, from, len) {
    var def = this.tierDef(tierKey);
    var count = def && def.levels ? def.levels : 0;
    var t = this.tierState(tierKey);
    var open = this.isTierUnlocked(tierKey);
    var rows = [];
    var first = from ? Math.max(1, from | 0) : 1;
    var last = len ? Math.min(count, first + (len | 0) - 1) : count;
    for (var n = first; n <= last; n++) {
      var lv = t.levels[n];
      rows.push({
        level: n,
        stars: lv ? lv.stars : 0,
        bestMs: lv ? lv.bestMs : 0,
        played: !!(lv && lv.plays),
        unlocked: open && n <= t.unlocked
      });
    }
    return rows;
  };

  Progress.prototype.totals = function () {
    return {
      totalStars: this.state.totalStars,
      solvedCount: this.state.solvedCount,
      clearedCount: this.state.clearedCount
    };
  };

  /* Highest unlocked, not-yet-3-starred level — "Play" on the home screen. */
  Progress.prototype.nextLevel = function (tierKey) {
    var t = this.tierState(tierKey);
    var def = this.tierDef(tierKey);
    var max = def && def.levels ? def.levels : t.unlocked;
    for (var n = 1; n <= Math.min(t.unlocked, max); n++) {
      var lv = t.levels[n];
      if (!lv || !lv.plays) return n;
    }
    return Math.min(t.unlocked, max);
  };

  Progress.defaultStars = defaultStars;
  return Progress;
});
